### PR TITLE
Upgrade jena and junit dependencies, improve tests

### PR DESCRIPTION
**Pull request by fkleedorfer**
With this commit, the tests provides more helpful output as to why they fail (if they do).

This PR reveals what it is that actually fails in https://github.com/pipauwel/IFCtoRDF/issues/28:

```
org.opentest4j.AssertionFailedError: Actual output differs from expected output:
  input: file C:\DATA\DEV\workspace\IFCtoRDF\target\test-classes\convertIFCFileToOutputTTL\PiPauwel_IFCtoRDF_test1.ttl
  expected output file: target\PiPauwel_IFCtoRDF_test1.ttl
  difference at line 2
  expected line:# imports: http://standards.buildingsmart.org/IFC/DEV/IFC4/ADD1/OWL
    actual line:# imports: http://standards.buildingsmart.org/IFC/DEV/IFC4/ADD2_TC1/OWL

	
org.opentest4j.AssertionFailedError: Actual output differs from expected output:
  input: file C:\DATA\DEV\workspace\IFCtoRDF\target\test-classes\convertIFCFileToOutputTTL\PiPauwel_IFCtoRDF_test10.ttl
  expected output file: target\PiPauwel_IFCtoRDF_test10.ttl
  difference at line 2
  expected line:# imports: http://standards.buildingsmart.org/IFC/DEV/IFC4/ADD1/OWL
    actual line:# imports: http://standards.buildingsmart.org/IFC/DEV/IFC4/ADD2_TC1/OWL
```
and there is the occasional
```
ERROR [main] (RDFWriter.java:1028) - *ERROR 2*: getResource failed for http://linkedbuildingdata.net/ifc/resources/_1
```
or 
```
ERROR [main] (IfcSpfParser.java:189) - *ERROR 6*: Reference to non-existing line number in line: #1= IFCAPPLICATION(#3,$,$,$);
```

### CODE REVIEW

**Comment by lewismc** [comment]
Nice work @fkleedorfer please ping me if you want me to review any code. Thanks
@pipauwel I am still around :)

**Comment by pipauwel** [comment]
Thanks people, I fully agree that tests can be improved. The help is much appreciated.

**Comment by pipauwel** [comment]
I have not looked in detail yet, but I have a small note about the occasional:
`ERROR [main] (IfcSpfParser.java:189) - *ERROR 6*: Reference to non-existing line number in line: #1= IFCAPPLICATION(#3,$,$,$);`

These errors are meant to pop up (as messages), because these specific test files are faulty IFC input files (indeed the line number is non-existing). So this test tests whether those errors are caught, output is zero, and code proceeds.

I'll repeat that this error handling and testing strategy needs to be improved.

**Comment by lewismc** [comment]
@fkleedorfer looks like there is a merge conflict. Can you update and we can stabilize? Thank you

**Comment by fkleedorfer** [comment]
done

**Comment by lewismc** [comment]
Hi @fkleedorfer this is an extremely difficult pull request to review. I would like to suggest in the future, if possible, keep your pull requests smaller. For example, split out the upgrades to jena, junit into two separate pull requests. With that being said, I will try my best to review.

**Comment by lewismc** [comment]
Actually @fkleedorfer is this PR ready for review?

**Comment by fkleedorfer** [comment]
Er, sorry. I made this PR from the master branch of our fork. It turned out we wanted more changes and started to use the fork, merging more and more stuff into the branch. The first part of that is in #35. I am closing this PR in favor of that one.

**Pull request closed without merging**
